# Generated by Django 4.2.1 on 2023-05-23 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_department_course_course_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='lecturer_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.department'),
        ),
    ]
