# Generated by Django 4.2.1 on 2023-05-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_examschedule_exam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_color',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='related_course',
        ),
    ]
