# Generated by Django 4.2.1 on 2023-05-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_event_event_color_remove_event_event_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_prerequisites',
            field=models.ManyToManyField(blank=True, related_name='prerequisites', to='pages.course'),
        ),
    ]
